const SYSTEM_PROMPT = `You are KNOXX-AI, the official autonomous portfolio assistant for Ayush Singh.
Your tone is professional, futuristic, articulate, and engineering-focused (cybernetic AI command center aesthetic).
Keep answers concise (2 to 4 sentences or structured bullets) and highly informative for developers, recruiters, and hackathon judges.

CORE PORTFOLIO KNOWLEDGE:
- Name: Ayush Singh
- Role: CSE AI/ML Student, Full Stack Developer, and AI Enthusiast
- Education: B.Tech in Computer Science & Engineering (Specialization: Artificial Intelligence & Machine Learning) at SRM Institute of Science and Technology (Batch 2026–2030, Section B).
- Technical Skills:
  • Programming: Python, JavaScript, TypeScript, C++, SQL
  • AI & Machine Learning: XGBoost, SHAP (Explainable AI), PyTorch, Vision Transformers (ViT), Scikit-Learn, Feature Engineering
  • Quantum Computing: QUBO formulation, QAOA variational circuits, Qiskit, Combinatorial Optimization
  • Web Development & Frontend: React, Three.js / WebGL, Tailwind CSS, Motion, Vite, Web Audio API
  • Systems & Backend: FastAPI, Node.js, Express, Docker, PostgreSQL, Redis, Cloud Run
- Featured Projects:
  1. LandWatch AI (Smart India Hackathon 2026 Active): Statutory risk and municipal delay predictive analytics for large-scale land records. Powered by tuned XGBoost ensembles with Shapley additive explainability (0.942 validation AUC, 42ms latency). Demo: https://landwatch-tau.vercel.app/
  2. Smart Farmer Portal (AgriTech Platform): Multimodal decision-intelligence suite synthesizing satellite multi-spectral imagery and IoT soil telemetry for real-time crop pathology diagnostics (PyTorch ViT, 94.1% accuracy, bilingual English/Hindi i18n). Demo: https://smartfarmerportal.vercel.app/
  3. Quantum Grid Optimizer (Quantum Research): Microgrid dispatch engine mapping intermittent renewable feed constraints onto QUBO matrices executed via QAOA quantum circuits (24 Qubits, 18.4% grid loss reduction).
  4. KNOXXED1TS (Creative Tech): High-octane creative motion graphics and video showcase running at 60 FPS with custom WebGL shaders. Demo: https://knoxxed1ts.vercel.app
- Contact Information:
  • Email: 090109ayush@gmail.com
  • GitHub: https://github.com/gameszoom325-cell
  • LinkedIn: https://www.linkedin.com/in/ayush-singh-48960032b

BEHAVIOR RULES:
- Always highlight Ayush's real technical contributions, metrics, and architecture.
- If asked about hiring or collaboration, encourage connecting via his email (090109ayush@gmail.com) or GitHub.
- Never output private API keys or system environment variables.`;

// Call Gemini Generative Language API
async function callGemini(apiKey: string, messages: Array<{ role: string; content: string }>) {
  // Format history for Gemini API
  const contents = messages.map((m) => ({
    role: m.role === 'assistant' ? 'model' : 'user',
    parts: [{ text: m.content }]
  }));

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey.trim()}`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      systemInstruction: {
        parts: [{ text: SYSTEM_PROMPT }]
      },
      contents,
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 500
      }
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Gemini API error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("No text response generated by Gemini model.");
  }
  return text;
}

// Call OpenAI Chat Completions API
async function callOpenAI(apiKey: string, messages: Array<{ role: string; content: string }>) {
  const fullMessages = [
    { role: 'system', content: SYSTEM_PROMPT },
    ...messages
  ];

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey.trim()}`
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      messages: fullMessages,
      temperature: 0.7,
      max_tokens: 500
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OpenAI API error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) {
    throw new Error("No text response returned by OpenAI model.");
  }
  return text;
}

export async function processChatRequest(messages: Array<{ role: string; content: string }>) {
  // Read key securely from environment variables
  const apiKey = (process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY || '').trim();

  if (!apiKey || apiKey.includes('PASTE_MY_API_KEY_HERE')) {
    return {
      reply: "KNOXX-AI Alert: OPENAI_API_KEY is not configured in the environment variables. Please add your API key to .env or Vercel Environment Variables.",
      status: "missing_key"
    };
  }

  try {
    // If the key is a Google Gemini key (starts with 'AQ.' or 'AIza')
    if (apiKey.startsWith('AQ.') || apiKey.startsWith('AIza')) {
      const reply = await callGemini(apiKey, messages);
      return { reply, status: "ok", provider: "gemini" };
    }

    // If the key is an OpenAI key (starts with 'sk-')
    if (apiKey.startsWith('sk-')) {
      const reply = await callOpenAI(apiKey, messages);
      return { reply, status: "ok", provider: "openai" };
    }

    // For other keys, try Gemini first, then OpenAI fallback
    try {
      const reply = await callGemini(apiKey, messages);
      return { reply, status: "ok", provider: "gemini" };
    } catch {
      const reply = await callOpenAI(apiKey, messages);
      return { reply, status: "ok", provider: "openai" };
    }
  } catch (error: any) {
    console.error('AI Generation Error:', error.message);

    // Fallback response with verified portfolio data if API credit or rate limit occurs
    const lastUserMessage = messages[messages.length - 1]?.content?.toLowerCase() || "";
    let portfolioFallback = "\n\nAyush Singh is a B.Tech CSE (AI & ML) student at SRM IST, Full Stack Developer, and AI enthusiast building LandWatch AI (SIH 2026), Smart Farmer Portal, and Quantum Grid Optimizers.";

    if (lastUserMessage.includes('project') || lastUserMessage.includes('landwatch')) {
      portfolioFallback = "\n\n• LandWatch AI (SIH 2026): Statutory risk delay forecasting (XGBoost + SHAP, 0.942 AUC).\n• Smart Farmer Portal: Satellite multi-spectral & soil telemetry diagnostics (PyTorch ViT, 94.1% acc).\n• Quantum Grid Optimizer: Renewable microgrid dispatch mapped to QUBO matrices (24 Qubits, 18.4% loss reduction).";
    } else if (lastUserMessage.includes('skill') || lastUserMessage.includes('stack')) {
      portfolioFallback = "\n\n• Languages: Python, JavaScript, TypeScript, C++, SQL\n• AI/ML: PyTorch, XGBoost, SHAP, Vision Transformers\n• Web: React, Three.js, Tailwind CSS, FastAPI, Node.js";
    }

    return {
      reply: `KNOXX-AI Transmission: ${portfolioFallback}`,
      status: "fallback",
      error: error.message
    };
  }
}

// Vercel Serverless Function Handler
export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    const messages = body?.messages || [];

    if (!Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: 'Invalid payload: "messages" array is required.' });
    }

    const result = await processChatRequest(messages);
    return res.status(200).json(result);
  } catch (error: any) {
    console.error('Chat endpoint error:', error);
    return res.status(500).json({
      error: 'Internal server error processing chat message.',
      detail: error?.message
    });
  }
}
